// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	clustercapacityreview "github.com/kubernetes-incubator/cluster-capacity/pkg/apis/clustercapacityreview"
	api "k8s.io/kubernetes/pkg/api"
	resource "k8s.io/kubernetes/pkg/api/resource"
	conversion "k8s.io/kubernetes/pkg/conversion"
	runtime "k8s.io/kubernetes/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ClusterCapacityReview_To_clustercapacityreview_ClusterCapacityReview,
		Convert_clustercapacityreview_ClusterCapacityReview_To_v1alpha1_ClusterCapacityReview,
		Convert_v1alpha1_ClusterCapacityReviewResult_To_clustercapacityreview_ClusterCapacityReviewResult,
		Convert_clustercapacityreview_ClusterCapacityReviewResult_To_v1alpha1_ClusterCapacityReviewResult,
		Convert_v1alpha1_ClusterCapacityReviewScheduleFailReason_To_clustercapacityreview_ClusterCapacityReviewScheduleFailReason,
		Convert_clustercapacityreview_ClusterCapacityReviewScheduleFailReason_To_v1alpha1_ClusterCapacityReviewScheduleFailReason,
		Convert_v1alpha1_ClusterCapacityReviewSpec_To_clustercapacityreview_ClusterCapacityReviewSpec,
		Convert_clustercapacityreview_ClusterCapacityReviewSpec_To_v1alpha1_ClusterCapacityReviewSpec,
		Convert_v1alpha1_ClusterCapacityReviewStatus_To_clustercapacityreview_ClusterCapacityReviewStatus,
		Convert_clustercapacityreview_ClusterCapacityReviewStatus_To_v1alpha1_ClusterCapacityReviewStatus,
		Convert_v1alpha1_Requirements_To_clustercapacityreview_Requirements,
		Convert_clustercapacityreview_Requirements_To_v1alpha1_Requirements,
		Convert_v1alpha1_Resources_To_clustercapacityreview_Resources,
		Convert_clustercapacityreview_Resources_To_v1alpha1_Resources,
	)
}

func autoConvert_v1alpha1_ClusterCapacityReview_To_clustercapacityreview_ClusterCapacityReview(in *ClusterCapacityReview, out *clustercapacityreview.ClusterCapacityReview, s conversion.Scope) error {
	if err := Convert_v1alpha1_ClusterCapacityReviewSpec_To_clustercapacityreview_ClusterCapacityReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterCapacityReviewStatus_To_clustercapacityreview_ClusterCapacityReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_v1alpha1_ClusterCapacityReview_To_clustercapacityreview_ClusterCapacityReview(in *ClusterCapacityReview, out *clustercapacityreview.ClusterCapacityReview, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCapacityReview_To_clustercapacityreview_ClusterCapacityReview(in, out, s)
}

func autoConvert_clustercapacityreview_ClusterCapacityReview_To_v1alpha1_ClusterCapacityReview(in *clustercapacityreview.ClusterCapacityReview, out *ClusterCapacityReview, s conversion.Scope) error {
	if err := Convert_clustercapacityreview_ClusterCapacityReviewSpec_To_v1alpha1_ClusterCapacityReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_clustercapacityreview_ClusterCapacityReviewStatus_To_v1alpha1_ClusterCapacityReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_clustercapacityreview_ClusterCapacityReview_To_v1alpha1_ClusterCapacityReview(in *clustercapacityreview.ClusterCapacityReview, out *ClusterCapacityReview, s conversion.Scope) error {
	return autoConvert_clustercapacityreview_ClusterCapacityReview_To_v1alpha1_ClusterCapacityReview(in, out, s)
}

func autoConvert_v1alpha1_ClusterCapacityReviewResult_To_clustercapacityreview_ClusterCapacityReviewResult(in *ClusterCapacityReviewResult, out *clustercapacityreview.ClusterCapacityReviewResult, s conversion.Scope) error {
	out.PodName = in.PodName
	out.ReplicasOnNodes = *(*map[string]int)(unsafe.Pointer(&in.ReplicasOnNodes))
	out.FailSummary = *(*map[string]int)(unsafe.Pointer(&in.FailSummary))
	return nil
}

func Convert_v1alpha1_ClusterCapacityReviewResult_To_clustercapacityreview_ClusterCapacityReviewResult(in *ClusterCapacityReviewResult, out *clustercapacityreview.ClusterCapacityReviewResult, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCapacityReviewResult_To_clustercapacityreview_ClusterCapacityReviewResult(in, out, s)
}

func autoConvert_clustercapacityreview_ClusterCapacityReviewResult_To_v1alpha1_ClusterCapacityReviewResult(in *clustercapacityreview.ClusterCapacityReviewResult, out *ClusterCapacityReviewResult, s conversion.Scope) error {
	out.PodName = in.PodName
	out.ReplicasOnNodes = *(*map[string]int)(unsafe.Pointer(&in.ReplicasOnNodes))
	out.FailSummary = *(*map[string]int)(unsafe.Pointer(&in.FailSummary))
	return nil
}

func Convert_clustercapacityreview_ClusterCapacityReviewResult_To_v1alpha1_ClusterCapacityReviewResult(in *clustercapacityreview.ClusterCapacityReviewResult, out *ClusterCapacityReviewResult, s conversion.Scope) error {
	return autoConvert_clustercapacityreview_ClusterCapacityReviewResult_To_v1alpha1_ClusterCapacityReviewResult(in, out, s)
}

func autoConvert_v1alpha1_ClusterCapacityReviewScheduleFailReason_To_clustercapacityreview_ClusterCapacityReviewScheduleFailReason(in *ClusterCapacityReviewScheduleFailReason, out *clustercapacityreview.ClusterCapacityReviewScheduleFailReason, s conversion.Scope) error {
	out.FailType = in.FailType
	out.FailMessage = in.FailMessage
	return nil
}

func Convert_v1alpha1_ClusterCapacityReviewScheduleFailReason_To_clustercapacityreview_ClusterCapacityReviewScheduleFailReason(in *ClusterCapacityReviewScheduleFailReason, out *clustercapacityreview.ClusterCapacityReviewScheduleFailReason, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCapacityReviewScheduleFailReason_To_clustercapacityreview_ClusterCapacityReviewScheduleFailReason(in, out, s)
}

func autoConvert_clustercapacityreview_ClusterCapacityReviewScheduleFailReason_To_v1alpha1_ClusterCapacityReviewScheduleFailReason(in *clustercapacityreview.ClusterCapacityReviewScheduleFailReason, out *ClusterCapacityReviewScheduleFailReason, s conversion.Scope) error {
	out.FailType = in.FailType
	out.FailMessage = in.FailMessage
	return nil
}

func Convert_clustercapacityreview_ClusterCapacityReviewScheduleFailReason_To_v1alpha1_ClusterCapacityReviewScheduleFailReason(in *clustercapacityreview.ClusterCapacityReviewScheduleFailReason, out *ClusterCapacityReviewScheduleFailReason, s conversion.Scope) error {
	return autoConvert_clustercapacityreview_ClusterCapacityReviewScheduleFailReason_To_v1alpha1_ClusterCapacityReviewScheduleFailReason(in, out, s)
}

func autoConvert_v1alpha1_ClusterCapacityReviewSpec_To_clustercapacityreview_ClusterCapacityReviewSpec(in *ClusterCapacityReviewSpec, out *clustercapacityreview.ClusterCapacityReviewSpec, s conversion.Scope) error {
	out.Templates = *(*[]api.Pod)(unsafe.Pointer(&in.Templates))
	out.Replicas = in.Replicas
	out.PodRequirements = *(*[]*clustercapacityreview.Requirements)(unsafe.Pointer(&in.PodRequirements))
	return nil
}

func Convert_v1alpha1_ClusterCapacityReviewSpec_To_clustercapacityreview_ClusterCapacityReviewSpec(in *ClusterCapacityReviewSpec, out *clustercapacityreview.ClusterCapacityReviewSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCapacityReviewSpec_To_clustercapacityreview_ClusterCapacityReviewSpec(in, out, s)
}

func autoConvert_clustercapacityreview_ClusterCapacityReviewSpec_To_v1alpha1_ClusterCapacityReviewSpec(in *clustercapacityreview.ClusterCapacityReviewSpec, out *ClusterCapacityReviewSpec, s conversion.Scope) error {
	out.Templates = *(*[]api.Pod)(unsafe.Pointer(&in.Templates))
	out.Replicas = in.Replicas
	out.PodRequirements = *(*[]*Requirements)(unsafe.Pointer(&in.PodRequirements))
	return nil
}

func Convert_clustercapacityreview_ClusterCapacityReviewSpec_To_v1alpha1_ClusterCapacityReviewSpec(in *clustercapacityreview.ClusterCapacityReviewSpec, out *ClusterCapacityReviewSpec, s conversion.Scope) error {
	return autoConvert_clustercapacityreview_ClusterCapacityReviewSpec_To_v1alpha1_ClusterCapacityReviewSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterCapacityReviewStatus_To_clustercapacityreview_ClusterCapacityReviewStatus(in *ClusterCapacityReviewStatus, out *clustercapacityreview.ClusterCapacityReviewStatus, s conversion.Scope) error {
	out.CreationTimestamp = in.CreationTimestamp
	out.Replicas = in.Replicas
	out.FailReason = (*clustercapacityreview.ClusterCapacityReviewScheduleFailReason)(unsafe.Pointer(in.FailReason))
	out.Pods = *(*[]*clustercapacityreview.ClusterCapacityReviewResult)(unsafe.Pointer(&in.Pods))
	return nil
}

func Convert_v1alpha1_ClusterCapacityReviewStatus_To_clustercapacityreview_ClusterCapacityReviewStatus(in *ClusterCapacityReviewStatus, out *clustercapacityreview.ClusterCapacityReviewStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCapacityReviewStatus_To_clustercapacityreview_ClusterCapacityReviewStatus(in, out, s)
}

func autoConvert_clustercapacityreview_ClusterCapacityReviewStatus_To_v1alpha1_ClusterCapacityReviewStatus(in *clustercapacityreview.ClusterCapacityReviewStatus, out *ClusterCapacityReviewStatus, s conversion.Scope) error {
	out.CreationTimestamp = in.CreationTimestamp
	out.Replicas = in.Replicas
	out.FailReason = (*ClusterCapacityReviewScheduleFailReason)(unsafe.Pointer(in.FailReason))
	out.Pods = *(*[]*ClusterCapacityReviewResult)(unsafe.Pointer(&in.Pods))
	return nil
}

func Convert_clustercapacityreview_ClusterCapacityReviewStatus_To_v1alpha1_ClusterCapacityReviewStatus(in *clustercapacityreview.ClusterCapacityReviewStatus, out *ClusterCapacityReviewStatus, s conversion.Scope) error {
	return autoConvert_clustercapacityreview_ClusterCapacityReviewStatus_To_v1alpha1_ClusterCapacityReviewStatus(in, out, s)
}

func autoConvert_v1alpha1_Requirements_To_clustercapacityreview_Requirements(in *Requirements, out *clustercapacityreview.Requirements, s conversion.Scope) error {
	out.PodName = in.PodName
	out.Resources = (*clustercapacityreview.Resources)(unsafe.Pointer(in.Resources))
	out.NodeSelectors = *(*map[string]string)(unsafe.Pointer(&in.NodeSelectors))
	return nil
}

func Convert_v1alpha1_Requirements_To_clustercapacityreview_Requirements(in *Requirements, out *clustercapacityreview.Requirements, s conversion.Scope) error {
	return autoConvert_v1alpha1_Requirements_To_clustercapacityreview_Requirements(in, out, s)
}

func autoConvert_clustercapacityreview_Requirements_To_v1alpha1_Requirements(in *clustercapacityreview.Requirements, out *Requirements, s conversion.Scope) error {
	out.PodName = in.PodName
	out.Resources = (*Resources)(unsafe.Pointer(in.Resources))
	out.NodeSelectors = *(*map[string]string)(unsafe.Pointer(&in.NodeSelectors))
	return nil
}

func Convert_clustercapacityreview_Requirements_To_v1alpha1_Requirements(in *clustercapacityreview.Requirements, out *Requirements, s conversion.Scope) error {
	return autoConvert_clustercapacityreview_Requirements_To_v1alpha1_Requirements(in, out, s)
}

func autoConvert_v1alpha1_Resources_To_clustercapacityreview_Resources(in *Resources, out *clustercapacityreview.Resources, s conversion.Scope) error {
	out.CPU = (*resource.Quantity)(unsafe.Pointer(in.CPU))
	out.Memory = (*resource.Quantity)(unsafe.Pointer(in.Memory))
	out.NvidiaGPU = (*resource.Quantity)(unsafe.Pointer(in.NvidiaGPU))
	out.OpaqueIntResources = *(*map[api.ResourceName]int64)(unsafe.Pointer(&in.OpaqueIntResources))
	return nil
}

func Convert_v1alpha1_Resources_To_clustercapacityreview_Resources(in *Resources, out *clustercapacityreview.Resources, s conversion.Scope) error {
	return autoConvert_v1alpha1_Resources_To_clustercapacityreview_Resources(in, out, s)
}

func autoConvert_clustercapacityreview_Resources_To_v1alpha1_Resources(in *clustercapacityreview.Resources, out *Resources, s conversion.Scope) error {
	out.CPU = (*resource.Quantity)(unsafe.Pointer(in.CPU))
	out.Memory = (*resource.Quantity)(unsafe.Pointer(in.Memory))
	out.NvidiaGPU = (*resource.Quantity)(unsafe.Pointer(in.NvidiaGPU))
	out.OpaqueIntResources = *(*map[api.ResourceName]int64)(unsafe.Pointer(&in.OpaqueIntResources))
	return nil
}

func Convert_clustercapacityreview_Resources_To_v1alpha1_Resources(in *clustercapacityreview.Resources, out *Resources, s conversion.Scope) error {
	return autoConvert_clustercapacityreview_Resources_To_v1alpha1_Resources(in, out, s)
}
