// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package clustercapacityreview

import (
	api "k8s.io/kubernetes/pkg/api"
	resource "k8s.io/kubernetes/pkg/api/resource"
	conversion "k8s.io/kubernetes/pkg/conversion"
	runtime "k8s.io/kubernetes/pkg/runtime"
	reflect "reflect"
	time "time"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_clustercapacityreview_ClusterCapacityReview, InType: reflect.TypeOf(&ClusterCapacityReview{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_clustercapacityreview_ClusterCapacityReviewResult, InType: reflect.TypeOf(&ClusterCapacityReviewResult{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_clustercapacityreview_ClusterCapacityReviewScheduleFailReason, InType: reflect.TypeOf(&ClusterCapacityReviewScheduleFailReason{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_clustercapacityreview_ClusterCapacityReviewSpec, InType: reflect.TypeOf(&ClusterCapacityReviewSpec{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_clustercapacityreview_ClusterCapacityReviewStatus, InType: reflect.TypeOf(&ClusterCapacityReviewStatus{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_clustercapacityreview_Requirements, InType: reflect.TypeOf(&Requirements{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_clustercapacityreview_Resources, InType: reflect.TypeOf(&Resources{})},
	)
}

func DeepCopy_clustercapacityreview_ClusterCapacityReview(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ClusterCapacityReview)
		out := out.(*ClusterCapacityReview)
		out.TypeMeta = in.TypeMeta
		if err := DeepCopy_clustercapacityreview_ClusterCapacityReviewSpec(&in.Spec, &out.Spec, c); err != nil {
			return err
		}
		if err := DeepCopy_clustercapacityreview_ClusterCapacityReviewStatus(&in.Status, &out.Status, c); err != nil {
			return err
		}
		return nil
	}
}

func DeepCopy_clustercapacityreview_ClusterCapacityReviewResult(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ClusterCapacityReviewResult)
		out := out.(*ClusterCapacityReviewResult)
		out.PodName = in.PodName
		if in.ReplicasOnNodes != nil {
			in, out := &in.ReplicasOnNodes, &out.ReplicasOnNodes
			*out = make(map[string]int)
			for key, val := range *in {
				(*out)[key] = val
			}
		} else {
			out.ReplicasOnNodes = nil
		}
		if in.FailSummary != nil {
			in, out := &in.FailSummary, &out.FailSummary
			*out = make(map[string]int)
			for key, val := range *in {
				(*out)[key] = val
			}
		} else {
			out.FailSummary = nil
		}
		return nil
	}
}

func DeepCopy_clustercapacityreview_ClusterCapacityReviewScheduleFailReason(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ClusterCapacityReviewScheduleFailReason)
		out := out.(*ClusterCapacityReviewScheduleFailReason)
		out.FailType = in.FailType
		out.FailMessage = in.FailMessage
		return nil
	}
}

func DeepCopy_clustercapacityreview_ClusterCapacityReviewSpec(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ClusterCapacityReviewSpec)
		out := out.(*ClusterCapacityReviewSpec)
		if in.Templates != nil {
			in, out := &in.Templates, &out.Templates
			*out = make([]api.Pod, len(*in))
			for i := range *in {
				if newVal, err := c.DeepCopy(&(*in)[i]); err != nil {
					return err
				} else {
					(*out)[i] = *newVal.(*api.Pod)
				}
			}
		} else {
			out.Templates = nil
		}
		out.Replicas = in.Replicas
		if in.PodRequirements != nil {
			in, out := &in.PodRequirements, &out.PodRequirements
			*out = make([]*Requirements, len(*in))
			for i := range *in {
				if newVal, err := c.DeepCopy(&(*in)[i]); err != nil {
					return err
				} else {
					(*out)[i] = *newVal.(**Requirements)
				}
			}
		} else {
			out.PodRequirements = nil
		}
		return nil
	}
}

func DeepCopy_clustercapacityreview_ClusterCapacityReviewStatus(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ClusterCapacityReviewStatus)
		out := out.(*ClusterCapacityReviewStatus)
		if newVal, err := c.DeepCopy(&in.CreationTimestamp); err != nil {
			return err
		} else {
			out.CreationTimestamp = *newVal.(*time.Time)
		}
		out.Replicas = in.Replicas
		if in.FailReason != nil {
			in, out := &in.FailReason, &out.FailReason
			*out = new(ClusterCapacityReviewScheduleFailReason)
			**out = **in
		} else {
			out.FailReason = nil
		}
		if in.Pods != nil {
			in, out := &in.Pods, &out.Pods
			*out = make([]*ClusterCapacityReviewResult, len(*in))
			for i := range *in {
				if newVal, err := c.DeepCopy(&(*in)[i]); err != nil {
					return err
				} else {
					(*out)[i] = *newVal.(**ClusterCapacityReviewResult)
				}
			}
		} else {
			out.Pods = nil
		}
		return nil
	}
}

func DeepCopy_clustercapacityreview_Requirements(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*Requirements)
		out := out.(*Requirements)
		out.PodName = in.PodName
		if in.Resources != nil {
			in, out := &in.Resources, &out.Resources
			*out = new(Resources)
			if err := DeepCopy_clustercapacityreview_Resources(*in, *out, c); err != nil {
				return err
			}
		} else {
			out.Resources = nil
		}
		if in.NodeSelectors != nil {
			in, out := &in.NodeSelectors, &out.NodeSelectors
			*out = make(map[string]string)
			for key, val := range *in {
				(*out)[key] = val
			}
		} else {
			out.NodeSelectors = nil
		}
		return nil
	}
}

func DeepCopy_clustercapacityreview_Resources(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*Resources)
		out := out.(*Resources)
		if in.CPU != nil {
			in, out := &in.CPU, &out.CPU
			*out = new(resource.Quantity)
			**out = (*in).DeepCopy()
		} else {
			out.CPU = nil
		}
		if in.Memory != nil {
			in, out := &in.Memory, &out.Memory
			*out = new(resource.Quantity)
			**out = (*in).DeepCopy()
		} else {
			out.Memory = nil
		}
		if in.NvidiaGPU != nil {
			in, out := &in.NvidiaGPU, &out.NvidiaGPU
			*out = new(resource.Quantity)
			**out = (*in).DeepCopy()
		} else {
			out.NvidiaGPU = nil
		}
		if in.OpaqueIntResources != nil {
			in, out := &in.OpaqueIntResources, &out.OpaqueIntResources
			*out = make(map[api.ResourceName]int64)
			for key, val := range *in {
				(*out)[key] = val
			}
		} else {
			out.OpaqueIntResources = nil
		}
		return nil
	}
}
